export const toggleSwitch: string;
export const toggleSwitchCheckbox: string;
export const toggleSwitchCircle: string;
export const toggleSwitchDisabled: string;
export const toggleSwitchInner: string;
export const toggleSwitchInnerWithText: string;
export const toggleSwitchLabel: string;
export const toggleSwitchText: string;
export const toggleSwitchWrapper: string;
